import 'dart:convert';
import 'dart:io';
import 'package:path/path.dart' as p;

/// Walks ../../skills/roveflow/ and embeds each file as a base64 string in
/// lib/src/bundled_templates.g.dart. Run with:
///   dart run tool/sync_templates.dart
void main() {
  final pkg = Directory.current;
  final skillRoot =
      Directory(p.join(pkg.path, '..', '..', 'skills', 'roveflow'));
  if (!skillRoot.existsSync()) {
    stderr.writeln(
        'sync_templates: skill source not found at ${skillRoot.path}');
    exit(1);
  }

  final entries = <String, String>{};
  for (final f in skillRoot.listSync(recursive: true)) {
    if (f is! File) continue;
    final rel = p.relative(f.path, from: skillRoot.path);
    entries[rel] = base64.encode(f.readAsBytesSync());
  }

  final buf = StringBuffer()
    ..writeln('// GENERATED by tool/sync_templates.dart — do not edit.')
    ..writeln('// Regenerate after any change to ../../skills/roveflow/.')
    ..writeln('')
    ..writeln("import 'dart:convert';")
    ..writeln('')
    ..writeln('/// Bundled skill files, keyed by path relative to skills/roveflow/.')
    ..writeln('/// Values are decoded on-demand.')
    ..writeln('String bundledSkillFile(String relPath) {')
    ..writeln('  final encoded = _files[relPath];')
    ..writeln("  if (encoded == null) throw ArgumentError('No bundled file: \$relPath');")
    ..writeln('  return utf8.decode(base64.decode(encoded));')
    ..writeln('}')
    ..writeln('')
    ..writeln('Iterable<String> bundledSkillPaths() => _files.keys;')
    ..writeln('')
    ..writeln('const Map<String, String> _files = {');
  final sorted = entries.keys.toList()..sort();
  for (final k in sorted) {
    buf.writeln("  '${k.replaceAll("'", r"\'")}': '${entries[k]}',");
  }
  buf.writeln('};');

  final outPath = p.join(pkg.path, 'lib', 'src', 'bundled_templates.g.dart');
  File(outPath).writeAsStringSync(buf.toString());
  stdout.writeln(
      'sync_templates: wrote ${entries.length} files to $outPath');
}
